apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2023-09-24T17:42:21Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: build-volume
  resourceVersion: "1193985"
  uid: 1b02f3b2-5c7c-4dbe-83ce-bda9a46a812c
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: build-volume-claim
    namespace: argo
    resourceVersion: "1193853"
    uid: 11082e06-4600-4032-a841-2d7c7451a7b0
  hostPath:
    path: /home/vts1/build
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
status:
  phase: Bound
