apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sillypy-dag-template
spec:
  arguments:
    parameters:
      - name: image
        value: harbor.cgdevx-demo.demoapps.click/sillypy/sillypy
      - name: tag
        value: "0.2"
      - name: workload
        value: sillypy

  entrypoint: sillypy-ci
  volumes:
  - name: build
    persistentVolumeClaim:
      claimName: build-volume-claim
  - name: kaniko-secret
    secret:
      secretName: harbcred
      items:
        - key: .dockerconfigjson
          path: config.json

  templates:
  - name: sillypy-ci
    dag:
      tasks:
      - name: linter
        templateRef: 
          name: black-wft
          template: black
      - name: kaniko
        dependencies: [linter]
        templateRef: 
          name: kaniko-wft
          template: kaniko
      - name: trivy-fs-scan
        dependencies: [kaniko]
        templateRef:
          name: trivy-fs-scan-wft
          template: trivy-fs-scan
      - name: crane
        dependencies: [linter,kaniko,trivy-fs-scan]
        templateRef: 
            name: crane-wft
            template: crane
