kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: build-volume-claim
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
