apiVersion: v1
kind: PersistentVolume
metadata:
  name: build
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  #  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /home/vts1/build
