apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sillypy-dag-template
spec:
  arguments:
    parameters:
      - name: image
        value: harbor.cgdevx-demo.demoapps.click/sillypy/sillypy
      - name: tag
        value: "0.2"
      - name: workload
        value: sillypy
      - name: revision
        value: "v1.0"
      - name: repo
        value: git@github.com:CGDevX-Demo/workload-sillypy.git
  #  entrypoint: sillypy-ci
  entrypoint: git-clone
  volumes:
  - name: build
    persistentVolumeClaim:
      claimName: build-volume-claim
  - name: kaniko-secret
    secret:
      secretName: harbcred
      items:
        - key: .dockerconfigjson
          path: config.json

  templates:
  - name: sillypy-ci
    dag:
      tasks:
      - name: linter
        templateRef: 
          name: black-wft
          template: black
      - name: kaniko
        dependencies: [linter]
        templateRef: 
          name: kaniko-wft
          template: kaniko
      - name: trivy-fs-scan
        dependencies: [kaniko]
        templateRef:
          name: trivy-fs-scan-wft
          template: trivy-fs-scan
      - name: crane
        dependencies: [linter,kaniko,trivy-fs-scan]
        templateRef: 
            name: crane-wft
            template: crane
  - name: git-clone
    inputs:
      artifacts:
      - name: sillypy-src
        path: /src
        git:
          repo: git@github.com:CGDevX-Demo/workload-sillypy.git
          revision: "v1.0"
          sshPrivateKeySecret:
             name: id-rsa-github
             key: id_rsa_for_github
          depth: 1
    script:
        image: python:latest
        env:
          - name: WORKLOAD
            value: "{{workflow.parameters.workload}}"
        command: [sh]
        source: |
          git status && ls -lra && cat dockerfile
          mkdir /build/${WORKLOAD}
          cp -r * /build/${WORKLOAD}
          cd /build/${WORKLOAD}
          pwd
          echo "I've been here" > test.txt
        volumeMounts:
          - mountPath: "/build"
            name: build
        workingDir: /src

