apiVersion: v1
kind: Pod
metadata:
  labels:
    run: black
  name: black
  namespace: default
spec:
  containers:
  - image: pyfound/black
    imagePullPolicy: IfNotPresent
    name: black
    args: ["/bin/sh", "-c", "while true; do sleep 3600;done"]
    volumeMounts:
        - name: src-storage
          mountPath: /src
  volumes:
    - name: src-storage
      persistentVolumeClaim:
        claimName: build-claim
