apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sillypy-dag-template
spec:
  arguments:
    parameters:
      - name: image
        value: vtsarfin/ktest
      - name: tag
        value: 0.1
      - name: workload
        value: sillypy

  entrypoint: sillypy-ci
  volumes:
  - name: build
    persistentVolumeClaim:
      claimName: build-volume-claim
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json

  templates:
  - name: crane
    container:
      image: gcr.io/go-containerregistry/crane
      imagePullPolicy: IfNotPresent
      args: ["push", "/workspace/{{workflow.parameters.workload}}.tar", "{{workflow.parameters.image}}:{{workflow.parameters.tag}}"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /home/nonroot/.docker
        - name: build
          mountPath: /workspace

  - name: kaniko
      #    inputs:
#parameters:
#         - name: workload

    container:
      image: gcr.io/kaniko-project/executor
      imagePullPolicy: IfNotPresent
      args: ["--dockerfile=/workspace/dockerfile", "--no-push", "--tar-path=/workspace/{{workflow.parameters.workload}}.tar"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: build
          mountPath: /workspace
            
  - name: black
    container:
      image: pyfound/black
      imagePullPolicy: IfNotPresent
      command: ["black", "--check", "-v", "/{{workflow.parameters.workload}}"]
      volumeMounts:
        - name: build
          mountPath: "/{{workflow.parameters.workload}}"

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [echo, "{{inputs.parameters.message}}"]
  - name: badass
    inputs:
      parameters:
        - name: message
        - name: exit-code
          value: 0
    container:
      imagePullPolicy: IfNotPresent
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}} | tee >>/build/test.txt; exit {{inputs.parameters.exit-code}}"]
      volumeMounts:
      - name: build
        mountPath: /build
#---------------------------------------------------
  - name: sillypy-ci
    dag:
      tasks:
      - name: linter
        template: black
      - name: kaniko
        dependencies: [linter]
        template: kaniko
      - name: crane
        dependencies: [linter,kaniko]
        template: crane
